name: Akshay Anand
description: Software Engineer, Photographer, Artist
url: "https://akshayjha.com"
baseurl: ""

permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /work/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - .jekyll-cache
